project_id = "doqteforumjdugifxryl"

[functions.stream-proxy]
verify_jwt = false

[functions.fetch-match-result]
verify_jwt = false

[functions.cricket-api]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
