project_id = "doqteforumjdugifxryl"

[functions.stream-proxy]
verify_jwt = false

[functions.iframe-proxy]
verify_jwt = false

[functions.fetch-match-result]
verify_jwt = false

[functions.cricket-api]
verify_jwt = false

[functions.api-cricket]
verify_jwt = false

[functions.google-indexing]
verify_jwt = false

[functions.update-match-status]
verify_jwt = false

[functions.extract-m3u8]
verify_jwt = false

[functions.auto-sync-scores]
verify_jwt = false

[functions.sync-api-scores]
verify_jwt = false

[functions.sync-points-table]
verify_jwt = false

[functions.sync-match-nrr]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.sitemap-ping]
verify_jwt = false

[functions.scrape-football-scores]
verify_jwt = false

[functions.increment-football-timer]
verify_jwt = false

[functions.scrape-cricket-matches]
verify_jwt = false
